### ISSUE TITLE
Commit Correct HSR RedBox crashes booting process

### ISSUE THREAD

**Issue by ildar1992** [Microchip-Ethernet/EVB-KSZ9477#11]
Commits before **Correct HSR RedBox implementation by using driver to forward frames a… (474171e03648cb47907e633a2fefeab2a766e69e)** compiles and works well. But when applying upper commit Linux Kernel compiles successfully, but when booting it sends the following message:
`
Starting kernel ...

data abort
pc : [<22000a48>]          lr : [<00000020>]
sp : 2242a8e8  ip : 00003954     fp : 224298e4
r10: 2242a908  r9 : 2243a908     r8 : 00000000
r7 : 20008000  r6 : 00000024     r5 : 00000014  r4 : 224298bc
r3 : 3b641d02  r2 : 00000000     r1 : 000a0dff  r0 : 0000001c
Flags: nZCv  IRQs off  FIQs off  Mode SVC_32
Resetting CPU ...
`

**Comment by triha2work** [comment]
It is probably the kernel size is not set correctly in U-Boot environment so that the kernel is not loaded completely.  When using Linux to program the NAND chip the sizes are automatically calculated, but not Windows.
This size can be changed manually in U-Boot by using the setenv command.

**Comment by ildar1992** [comment]
Thank you!
