### ISSUE TITLE
RSTP port enable/disable

### ISSUE THREAD

**Issue by embeddman** [Microchip-Ethernet/EVB-KSZ9477#41]
Hi!
In sysfs it has ability to turn on/off port in RSTP via /sys/class/net/eth0/sw0/0_stp_on. But it works strange. For example, if there's link on a port, to turn off the port from RSTP via sending 0 to 0_stp_on works, but until reconnecting the port, the next time it's working again. Is it possible to turn on/off port in RSTP permanently, not until link changing?

**Comment by triha2work** [comment]
It was not designed to remove the port from RSTP participation.  You can use the driver parameter "stp" for that purpose.  "stp=1" means all ports; "stp=3" means ports 1 and 2.

**Comment by embeddman** [comment]
Thanks!
